language: generic
dist: xenial
sudo: required
script:
- bash test-hello.sh
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: KtiZgYEK0jYhZqdJrCLX8yXSrLZOYcTfxdsfXIq6tCNhGd7XgM3DVEfTOvDU0XfBTE5yoWZgFXtHodiwvjWpRojU5ATNvVamlg6B3AhIRjlhBtHTRX1RAqcAvclBkati5at+RK6r1RP6Y8eIjRS+Bn/ViQeiJTISniyS3GW+dy+Hd1gHty24BSoVmHhhItECdCDcPPeLHsyzpMlhfz+HfvU/EKwpeaMbgMVWxuN11QvmOxN1ZGOj+2kVj4lgkUPq8zVjAnM761cbo69mNXkT8sFZTbd6zNPfo1g60IKgk6yAsnLot0PvfASHbCX3zoYIiJHt1XZSh+ipqu0DKn6i6y3IX14C6I0QoJu63Hn1DBIa5T2Oiv/6iFi9QL4t4cgtHQigLUmysS/6lWSa2S5Mx1Q53yHbFLhp9Baw0jKn1z4MWMjFU+TU2B0pn8ht1mgy+CjY3Dmtb2FydwONtwtsvplzybVzVLk7nZryI4rHEHwUMvdop7L2Ixz/f6mX6ak/2z82Q6EN9vp6wUWPcOORw+h0wqUN7gxNta8591D0YWZX0RqRsq4WRjsQoyMe7/uGoLyv1tToH/MiDBaA1dqDgcdRfPNcUoty9YljCjFltu8PEfjRoJGoAB5Wl0Lq8JnT/DBQn7InkJVg3hDRfLfB+p6AIOHBCovBS66i6XNarO0=
  file: hello.sh
  on:
    repo: Bruj0Corp/hello-machine
    tags: true

