language: generic
dist: xenial
sudo: required
script:
- bash test-hello.sh
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: BaDpoPKZZv+TeZEcsDyQYG6+LSgmXM+z09QIHl/T3SGocVDno+YBvxYmaFNvm2KbmmgTuJTlGUcfl1t1V6x+40dtkEntrO5+r1Y/ysRdUagb6Jqse6SX5oWRL+p5ezzG2fzhVRT+ouzRmrFh8PqVDdG2vC0lXfQoDc5KnJpLexcPcb0tKDY1iwHH15O/2US1y28CyZRihoEQ6CbJCjtvzp3vCW5HH+Q4OqIly+AmgH1eM7CB3SDN/JDJ+UnOgGLI0Ren3qiADq8T2G/BevB3Pqjn5Jb2/HRaPSJS+aCOFjac4C0Y0Tgw3YNxcjzfhpjZq7V7n0lmC2HqfauQcbbe5UyXoQo0ggFrqlkbfTmrw5A3uHM/qWDhHkq6cA7PmETeoDDwbXJlpf0uw9l564ZI4PYKdx9P+oNZpmjHPYeoXKRdvDA/CFhrxQnAj9oOyTBt5jga4YeJ3N77gxcG//EvO05FwcqDvdxlpNcBQIKaxLCmY+9MPcOhxPD9gk0dn0F2I8KuscVo3N0QPyPZ2oeMA9fbNbss+K3WPoZ56BpiJo8gmQK5G6tPzOpmTsj0Lb1kyl0+VdR3ixXPhUP2nEmBR6QzLGYa4jePPUV6R3UDyY6ZugHe13zkfNvMTM1dGL/JOh3qB/W8Kx/NrGQ3Qw/PjFgyVmqCBbemGtRB1ObhL+w=
  file: hello.sh
  on:
    repo: Bruj0Corp/hello-machine
    tags: true
