language: generic
dist: xenial
sudo: required
script:
- bash test-hello.sh
deploy:
  provider: releases
  api_key:
    secure: XoWxSdQiIpDVeInAFK7UhWlsk0itgeMTbBttoPuM5UskeDAyoD5ZDXxSPSr6aEM4Dzs412x2DtCzFUG+K/pDvrB49kBsioiaNSZlS2TDN408oFRtMncuzbHUKtyPp2xRCwWx3rPKXhKdpd1YTL5n0UOGeQW+/RVPEm8jjwaUnDL+ELMqq5oQAy2N2SVJhpEdo5SkoA40+YdeEjYOfWh7ntddomleAHkEE80U5ERL2j/VV0IesijkPv+BhLbnWYgq6qXCU1n8ul3KitkPe+CYIwanlSgMpK4LMVlDX9HvAiP/a+OF60bviJ0BtQ+FOQREr8QJmCQ8qAwQBiXwsL6gF20KOKqzyDOfT4zEuiktXDbOb2anTgV3Tkq98yHC07DYI+kBjtlZDAJjnWFrsT6Y71rDe0SWuIMwgf/K9/LUgWe/hwqONKP1QTzJw6E3Ra9f51JXxjw7woE6PDsCE+N79AsszJIb07MhUky2E5WEVU0ONYqm+Br9F2TtDTV4ZsZzUZVwIN5yCwMo+xU6tj6U2BSRCXf5/Zkok2Do5CGUL63Jj79GhCPxlV5QemBfRMO63j+m6RmvIyekUr7IFgzFPWrKrVyI4/L+ihg6fYMJlNGMzGbSRPIWD//StDw64lU1W5vX8FZd9Vysna9+ftd8amoyUJzUV4/JWUkjo4Lksis=
  file: hello.sh
  on:
    repo: Bruj0Corp/hello-machine
